=== ubccr/xdmod/tests/artifacts/xdmod/schema/get-menus.spec.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "get-menus",
    "type": "array",
    "items": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "text": {
          "type":"string"
        },
        "id": {
          "type":"string"
        },
        "group_by": {
          "type":"string"
        },
        "query_group": {
          "type":"string"
        },
        "category": {
          "type":"string"
        },
        "realm": {
          "type":"string"
        },
        "defaultChartSettings": {
          "type":"string"
        },
        "chartSettings": {
          "type":"string"
        },
        "node_type": {
          "type":"string"
        },
        "iconCls": {
          "type":"string"
        },
        "description": {
          "type":"string"
        },
        "leaf": {
          "type":"boolean"
        },
        "disabled": {
          "type":"boolean"
        }
      },
      "required": [
        "text",
        "id",
        "node_type",
        "iconCls",
        "leaf"
      ]
    }
  }

=== ubccr/xdmod/tests/artifacts/xdmod/user_admin/output/resourcespecifications/get_menus-principal-1.json
[
    {
        "text": "Resource Specifications Summary",
        "id": "group_by_ResourceSpecifications_none",
        "group_by": "none",
        "query_group": "tg_usage",
        "category": "ResourceSpecifications",
        "realm": "ResourceSpecifications",
        "defaultChartSettings": "{\"dataset_type\":\"timeseries\",\"display_type\":\"line\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "chartSettings": "{\"dataset_type\":\"timeseries\",\"display_type\":\"line\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "node_type": "group_by",
        "iconCls": "menu",
        "description": "Screwdriver",
        "leaf": false
    },
    {
        "text": "Resource Specifications by Resource",
        "id": "group_by_ResourceSpecifications_resource",
        "group_by": "resource",
        "query_group": "tg_usage",
        "category": "ResourceSpecifications",
        "realm": "ResourceSpecifications",
        "defaultChartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "chartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "node_type": "group_by",
        "iconCls": "menu",
        "description": "Resource",
        "leaf": false
    },
    {
        "text": "Resource Specifications by Resource Allocation Type",
        "id": "group_by_ResourceSpecifications_resource_allocation_type",
        "group_by": "resource_allocation_type",
        "query_group": "tg_usage",
        "category": "ResourceSpecifications",
        "realm": "ResourceSpecifications",
        "defaultChartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "chartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "node_type": "group_by",
        "iconCls": "menu",
        "description": "Resource Allocation Type",
        "leaf": false
    },
    {
        "text": "Resource Specifications by Resource Type",
        "id": "group_by_ResourceSpecifications_resource_type",
        "group_by": "resource_type",
        "query_group": "tg_usage",
        "category": "ResourceSpecifications",
        "realm": "ResourceSpecifications",
        "defaultChartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "chartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "node_type": "group_by",
        "iconCls": "menu",
        "description": "Resource Type",
        "leaf": false
    },
    {
        "text": "Resource Specifications by Service Provider",
        "id": "group_by_ResourceSpecifications_provider",
        "group_by": "provider",
        "query_group": "tg_usage",
        "category": "ResourceSpecifications",
        "realm": "ResourceSpecifications",
        "defaultChartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "chartSettings": "{\"dataset_type\":\"aggregate\",\"display_type\":\"h_bar\",\"combine_type\":\"stack\",\"limit\":3,\"offset\":0,\"log_scale\":\"n\",\"show_legend\":\"y\",\"show_trend_line\":\"n\",\"show_error_bars\":\"n\",\"show_guide_lines\":\"y\",\"show_aggregate_labels\":\"n\",\"show_error_labels\":\"n\",\"enable_errors\":\"y\",\"enable_trend_line\":\"y\"}",
        "node_type": "group_by",
        "iconCls": "menu",
        "description": "Service Provider",
        "leaf": false
    },
    {
        "text": "",
        "id": "-111",
        "node_type": "separator",
        "iconCls": "blank",
        "leaf": true,
        "disabled": true
    }
]
