=== ubccr/xdmod/configuration/etl/etl_schemas.d/storage/usage.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Storage usage data",
    "description": "A representation of storage resource usage",
    "type": "object",
    "properties": {
        "resource": {
            "type": "string",
            "description": "Storage resource name",
            "maxLength": 200
        },
        "mountpoint": {
            "type": "string",
            "description": "Storage file system mountpoint directory",
            "maxLength": 255
        },
        "user": {
            "type": "string",
            "description": "Storage user's system username",
            "maxLength": 30
        },
        "pi": {
            "type": "string",
            "description": "Storage principal investigator's system username",
            "maxLength": 30
        },
        "dt": {
            "type": "string",
            "format": "date-time",
            "description": "Date and time usage data was recorded"
        },
        "file_count": {
            "type": "integer",
            "description": "Number of files",
            "minimum": 0,
            "maximum": 18446744073709551615
        },
        "logical_usage": {
            "type": "integer",
            "description": "Logical file system usage measured in bytes",
            "minimum": 0,
            "maximum": 18446744073709551615
        },
        "physical_usage": {
            "type": "integer",
            "description": "Physical file system usage measured in bytes",
            "minimum": 0,
            "maximum": 18446744073709551615
        },
        "soft_threshold": {
            "type": "integer",
            "description": "Soft threshold quota measured in bytes",
            "minimum": 0,
            "maximum": 18446744073709551615
        },
        "hard_threshold": {
            "type": "integer",
            "description": "Hard threshold quota measured in bytes",
            "minimum": 0,
            "maximum": 18446744073709551615
        }
    },
    "required": [
        "resource",
        "mountpoint",
        "user",
        "pi",
        "dt",
        "file_count",
        "logical_usage"
    ]
}

=== ubccr/xdmod/tests/artifacts/xdmod-test-artifacts/xdmod/referencedata/storage/recex/data-2018-12-29.json
[
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 809310,
    "hard_threshold": 25000001536000,
    "logical_usage": 492912512000,
    "mountpoint": "/data",
    "pi": "ibech",
    "resource": "recex",
    "soft_threshold": 25000001536000,
    "user": "ibech"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 105191992,
    "hard_threshold": 20000002048000,
    "logical_usage": 18024812544000,
    "mountpoint": "/data",
    "pi": "magwa",
    "resource": "recex",
    "soft_threshold": 20000002048000,
    "user": "magwa"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 32673,
    "hard_threshold": 10005000192000,
    "logical_usage": 9928160640000,
    "mountpoint": "/data",
    "pi": "sanma",
    "resource": "recex",
    "soft_threshold": 10000003072000,
    "user": "sanma"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 471,
    "hard_threshold": 1010008064000,
    "logical_usage": 124288000,
    "mountpoint": "/data",
    "pi": "fulma",
    "resource": "recex",
    "soft_threshold": 1000005632000,
    "user": "shttr"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 10403,
    "hard_threshold": 10005000192000,
    "logical_usage": 9219024768000,
    "mountpoint": "/data",
    "pi": "norpa",
    "resource": "recex",
    "soft_threshold": 10000003072000,
    "user": "norpa"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 943358,
    "hard_threshold": 10005000192000,
    "logical_usage": 3707438080000,
    "mountpoint": "/data",
    "pi": "aytinis",
    "resource": "recex",
    "soft_threshold": 10000003072000,
    "user": "aytinis"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 3,
    "hard_threshold": 2000003072000,
    "logical_usage": 35556608000,
    "mountpoint": "/data",
    "pi": "fulma",
    "resource": "recex",
    "soft_threshold": 1000001536000,
    "user": "setusca"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 1221229,
    "hard_threshold": 30000001024000,
    "logical_usage": 29203779072000,
    "mountpoint": "/data",
    "pi": "chaff",
    "resource": "recex",
    "soft_threshold": 30000001024000,
    "user": "chaff"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 2145969,
    "hard_threshold": 10005000192000,
    "logical_usage": 8958675584000,
    "mountpoint": "/data",
    "pi": "leske",
    "resource": "recex",
    "soft_threshold": 10000003072000,
    "user": "leske"
  },
  {
    "dt": "2018-12-29T13:12:08Z",
    "file_count": 1,
    "hard_threshold": 10005000192000,
    "logical_usage": 0,
    "mountpoint": "/data",
    "pi": "fulma",
    "resource": "recex",
    "soft_threshold": 10000003072000,
    "user": "camwa"
  }
]
